/* ═══════════════════════════════════════════════════════════════
   SDET-AI — main.js
   ═══════════════════════════════════════════════════════════════ */
(function () {
  'use strict';

  /* ── Config ──────────────────────────────────────────────────
     Waitlist backend. Create a free form at https://formspree.io,
     then replace YOUR_FORM_ID below with the real ID.
     Until then, submissions show a helpful error with a mailto
     fallback instead of silently pretending to succeed.        */
  const WAITLIST_ENDPOINT = 'https://formspree.io/f/YOUR_FORM_ID';

  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* ── Nav scroll state ───────────────────────────────────────── */
  const nav = document.getElementById('nav');
  const onScroll = () => nav.classList.toggle('scrolled', window.scrollY > 40);
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  /* ── Mobile menu ────────────────────────────────────────────── */
  const mobileBtn = document.getElementById('mobile-menu-toggle');
  const navLinks = document.getElementById('nav-links');

  mobileBtn.addEventListener('click', () => {
    const open = navLinks.classList.toggle('open');
    mobileBtn.setAttribute('aria-expanded', String(open));
  });

  navLinks.addEventListener('click', (e) => {
    if (e.target.tagName === 'A') {
      navLinks.classList.remove('open');
      mobileBtn.setAttribute('aria-expanded', 'false');
    }
  });

  /* ── Scroll reveal ──────────────────────────────────────────── */
  const revealEls = document.querySelectorAll('.reveal');
  if (prefersReducedMotion) {
    revealEls.forEach((el) => el.classList.add('visible'));
  } else {
    const ro = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (e.isIntersecting) {
          e.target.classList.add('visible');
          ro.unobserve(e.target);
        }
      });
    }, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' });
    revealEls.forEach((el) => ro.observe(el));
  }

  /* ── Demo tabs (WAI-ARIA tabs pattern) ──────────────────────── */
  const tabs = Array.from(document.querySelectorAll('.demo-tab[role="tab"]'));
  const panels = tabs.map((t) => document.getElementById(t.getAttribute('aria-controls')));

  function selectTab(index) {
    tabs.forEach((tab, i) => {
      const selected = i === index;
      tab.setAttribute('aria-selected', String(selected));
      tab.tabIndex = selected ? 0 : -1;
      panels[i].classList.toggle('active', selected);
      panels[i].hidden = !selected;
    });
  }

  tabs.forEach((tab, i) => {
    tab.addEventListener('click', () => selectTab(i));
    tab.addEventListener('keydown', (e) => {
      let next = null;
      if (e.key === 'ArrowDown' || e.key === 'ArrowRight') next = (i + 1) % tabs.length;
      if (e.key === 'ArrowUp' || e.key === 'ArrowLeft') next = (i - 1 + tabs.length) % tabs.length;
      if (e.key === 'Home') next = 0;
      if (e.key === 'End') next = tabs.length - 1;
      if (next !== null) {
        e.preventDefault();
        selectTab(next);
        tabs[next].focus();
      }
    });
  });

  /* ── Hero typing animation ──────────────────────────────────── */
  const heroCode = document.getElementById('hero-code');
  const heroStatus = document.getElementById('hero-status');

  // [cssClass, text] token pairs, typed in order.
  const CODE_TOKENS = [
    ['tk-cmt', '// Generated by SDET-AI · US-2041\n'],
    ['tk-kw', 'import'], ['tk-pln', ' { test, expect } '], ['tk-kw', 'from'],
    ['tk-pln', ' '], ['tk-str', "'@playwright/test'"], ['tk-pln', ';\n\n'],
    ['tk-fn', 'test'], ['tk-pln', '.'], ['tk-fn', 'describe'], ['tk-pln', '('],
    ['tk-str', "'US-2041: Login'"], ['tk-pln', ', () => {\n\n'],
    ['tk-pln', '  '], ['tk-fn', 'test'], ['tk-pln', '('],
    ['tk-str', "'redirects to dashboard'"], ['tk-pln', ', '],
    ['tk-kw', 'async'], ['tk-pln', ' ({ page }) => {\n'],
    ['tk-pln', '    '], ['tk-kw', 'await'], ['tk-pln', ' page.'], ['tk-fn', 'goto'],
    ['tk-pln', '('], ['tk-str', "'/login'"], ['tk-pln', ');\n'],
    ['tk-pln', '    '], ['tk-kw', 'await'], ['tk-pln', ' page.'], ['tk-fn', 'getByLabel'],
    ['tk-pln', '('], ['tk-str', "'Email'"], ['tk-pln', ').'], ['tk-fn', 'fill'],
    ['tk-pln', '(USER);\n'],
    ['tk-pln', '    '], ['tk-kw', 'await'], ['tk-pln', ' page.'], ['tk-fn', 'getByLabel'],
    ['tk-pln', '('], ['tk-str', "'Password'"], ['tk-pln', ').'], ['tk-fn', 'fill'],
    ['tk-pln', '(PASS);\n'],
    ['tk-pln', '    '], ['tk-kw', 'await'], ['tk-pln', ' page.'], ['tk-fn', 'getByRole'],
    ['tk-pln', '('], ['tk-str', "'button'"], ['tk-pln', ',\n      { name: '],
    ['tk-str', "'Sign in'"], ['tk-pln', ' }).'], ['tk-fn', 'click'], ['tk-pln', '();\n'],
    ['tk-pln', '    '], ['tk-kw', 'await'], ['tk-pln', ' '], ['tk-fn', 'expect'],
    ['tk-pln', '(page).'], ['tk-fn', 'toHaveURL'], ['tk-pln', '('],
    ['tk-str', "'/dashboard'"], ['tk-pln', ');\n'],
    ['tk-pln', '  });\n'],
    ['tk-pln', '});']
  ];

  function renderCodeInstantly() {
    const frag = document.createDocumentFragment();
    CODE_TOKENS.forEach(([cls, text]) => {
      const span = document.createElement('span');
      span.className = cls;
      span.textContent = text;
      frag.appendChild(span);
    });
    heroCode.innerHTML = '';
    heroCode.appendChild(frag);
    finishTyping();
  }

  function finishTyping() {
    if (heroStatus) {
      heroStatus.innerHTML = '<span class="ok" aria-hidden="true">●</span> spec generated';
    }
  }

  function typeCode() {
    const cursor = heroCode.querySelector('.typing-cursor');
    let tokenIdx = 0;
    let charIdx = 0;
    let currentSpan = null;

    function step() {
      if (tokenIdx >= CODE_TOKENS.length) {
        finishTyping();
        return;
      }
      const [cls, text] = CODE_TOKENS[tokenIdx];
      if (charIdx === 0) {
        currentSpan = document.createElement('span');
        currentSpan.className = cls;
        heroCode.insertBefore(currentSpan, cursor);
      }
      currentSpan.textContent += text[charIdx];
      charIdx++;
      if (charIdx >= text.length) {
        tokenIdx++;
        charIdx = 0;
      }
      setTimeout(step, 14 + Math.random() * 24);
    }

    step();
  }

  if (heroCode) {
    if (prefersReducedMotion) {
      renderCodeInstantly();
    } else {
      // Start typing when the terminal scrolls into view (or immediately if it already is).
      const typeObserver = new IntersectionObserver((entries, obs) => {
        if (entries.some((e) => e.isIntersecting)) {
          obs.disconnect();
          setTimeout(typeCode, 500);
        }
      }, { threshold: 0.2 });
      typeObserver.observe(heroCode);
    }
  }

  /* ── Waitlist form ──────────────────────────────────────────── */
  const form = document.getElementById('waitlist-form');
  const emailInput = document.getElementById('waitlist-email');
  const submitBtn = document.getElementById('waitlist-submit-btn');
  const formMsg = document.getElementById('form-msg');
  const toast = document.getElementById('toast');
  const toastMsg = document.getElementById('toast-message');
  let toastTimer = null;

  function showToast(message, isError) {
    toastMsg.textContent = message;
    toast.classList.toggle('error', Boolean(isError));
    toast.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => toast.classList.remove('show'), 5000);
  }

  function setFormMsg(message, kind) {
    formMsg.textContent = message;
    formMsg.className = 'form-msg' + (kind ? ' ' + kind : '');
  }

  form.addEventListener('submit', async (e) => {
    e.preventDefault();

    const email = emailInput.value.trim();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      emailInput.setAttribute('aria-invalid', 'true');
      setFormMsg('Please enter a valid email address.', 'error');
      emailInput.focus();
      return;
    }
    emailInput.removeAttribute('aria-invalid');

    // Honeypot: silently drop bot submissions.
    if (form.querySelector('.hp-field').value) return;

    if (WAITLIST_ENDPOINT.includes('YOUR_FORM_ID')) {
      setFormMsg('Signups are not wired up yet — email deveshvyas@sdet-ai.tech and you will be added by hand.', 'error');
      return;
    }

    submitBtn.disabled = true;
    setFormMsg('Joining…');

    try {
      const res = await fetch(WAITLIST_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify({ email, source: 'sdet-ai.tech landing' })
      });
      if (!res.ok) throw new Error('Request failed: ' + res.status);
      emailInput.value = '';
      setFormMsg("You're on the list — check your inbox for a confirmation.", 'success');
      showToast("You're on the waitlist! We'll be in touch soon.");
    } catch (err) {
      setFormMsg('Something went wrong. Please retry, or email deveshvyas@sdet-ai.tech directly.', 'error');
      showToast('Could not join the waitlist — please try again.', true);
    } finally {
      submitBtn.disabled = false;
    }
  });

  /* ── Footer year ────────────────────────────────────────────── */
  const yearEl = document.getElementById('year');
  if (yearEl) yearEl.textContent = String(new Date().getFullYear());

  /* ── Hero particles (skipped entirely under reduced motion) ── */
  const canvas = document.getElementById('particle-canvas');
  if (canvas && !prefersReducedMotion) {
    const ctx = canvas.getContext('2d');
    const COLORS = ['rgba(59,130,246,', 'rgba(139,92,246,', 'rgba(34,211,238,'];
    const COUNT = 50;
    let W, H, particles;
    let running = false;
    let rafId = null;

    function resize() {
      const rect = canvas.parentElement.getBoundingClientRect();
      W = canvas.width = rect.width;
      H = canvas.height = rect.height;
    }

    function mkp() {
      return {
        x: Math.random() * W,
        y: Math.random() * H,
        r: Math.random() * 1.5 + 0.4,
        vx: (Math.random() - 0.5) * 0.25,
        vy: (Math.random() - 0.5) * 0.25,
        alpha: Math.random() * 0.5 + 0.1,
        color: COLORS[Math.floor(Math.random() * COLORS.length)],
        life: Math.random() * 200 + 100,
        age: 0
      };
    }

    function draw() {
      if (!running) return;
      ctx.clearRect(0, 0, W, H);
      for (let i = 0; i < particles.length; i++) {
        const p = particles[i];
        p.x += p.vx; p.y += p.vy; p.age++;
        const lr = p.age / p.life;
        const fade = lr < 0.1 ? lr / 0.1 : lr > 0.8 ? 1 - (lr - 0.8) / 0.2 : 1;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
        ctx.fillStyle = p.color + (p.alpha * fade) + ')';
        ctx.fill();
        if (p.age >= p.life || p.x < 0 || p.x > W || p.y < 0 || p.y > H) {
          particles[i] = mkp();
        }
      }
      rafId = requestAnimationFrame(draw);
    }

    function start() {
      if (running) return;
      running = true;
      rafId = requestAnimationFrame(draw);
    }

    function stop() {
      running = false;
      if (rafId) cancelAnimationFrame(rafId);
    }

    resize();
    particles = Array.from({ length: COUNT }, mkp);

    // Only animate while the hero is on screen and the tab is visible.
    let heroVisible = false;
    new IntersectionObserver((entries) => {
      heroVisible = entries.some((e) => e.isIntersecting);
      heroVisible ? start() : stop();
    }).observe(canvas.parentElement);

    document.addEventListener('visibilitychange', () => {
      (document.hidden || !heroVisible) ? stop() : start();
    });

    window.addEventListener('resize', () => {
      resize();
      particles = Array.from({ length: COUNT }, mkp);
    }, { passive: true });
  }
})();
